In [1]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

pygame 2.1.2 (SDL 2.0.18, Python 3.10.2)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye_tree_eyeglasses.xml')
model = load_model(r"C:\Users\YUVRAJ\Desktop\Machine Learning\PROJECTS\Drowzy_detection\model")

In [16]:
mixer.init()
sound= mixer.Sound(r"C:\Users\YUVRAJ\Desktop\Machine Learning\PROJECTS\Drowzy_detection\alarm.wav")
cap = cv2.VideoCapture(1)
Score = 0
while True:
    
    # To read frame from the camera
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    
    # For converting gray scale of each frame
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    # For detecting faces of different size 
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        roi_gray = gray[y:y+h,x:x+w]
        roi_color = frame[y:y+h,x:x+w]
        
        # For detecting eye of different size 
        eyes= eye_cascade.detectMultiScale(roi_gray, scaleFactor= 1.1, minNeighbors=1)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (0,255,0), thickness=3 )
        
           
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+w]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        
        # If eyes are close
        if prediction[0][0]>0.50:
            cv2.putText(frame,'close',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>10):
                try:
                    sound.play()
                except:
                    pass
            
            
        # if eyes are open
        elif prediction[0][1]>0.50:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            

           
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[0.29488784 0.70511216]]
[[0.2787349  0.72126514]]
[[0.36036432 0.6396357 ]]
[[0.59979326 0.40020677]]
[[0.36572176 0.63427824]]
[[0.36572176 0.63427824]]
[[0.07503829 0.9249617 ]]
[[0.4358483  0.56415176]]
[[0.7063103 0.2936897]]
[[0.0324362 0.9675638]]
[[0.181337 0.818663]]
[[0.04233793 0.95766205]]
[[0.86372846 0.13627154]]
[[0.11666977 0.8833302 ]]
[[0.29159573 0.7084043 ]]
[[0.2459122  0.75408775]]
[[0.4829783  0.51702166]]
[[0.32541403 0.67458594]]
[[0.22206403 0.777936  ]]
[[0.04626838 0.9537316 ]]
[[0.91961986 0.08038007]]
[[0.98134816 0.01865185]]
[[0.93755263 0.06244731]]
[[0.9815839  0.01841612]]
[[0.91433525 0.08566477]]
[[0.97460294 0.02539708]]
[[0.9943963  0.00560363]]
[[0.9823277  0.01767227]]
[[0.97421604 0.02578392]]
[[0.81705993 0.18294011]]
[[0.88121665 0.11878337]]
[[0.4602163 0.5397837]]
[[0.00824138 0.99175864]]
[[0.52212095 0.47787908]]
[[0.15384786 0.8461522 ]]
[[0.04771465 0.9522853 ]]
[[0.29445818 0.7055418 ]]
[[0.4248738  0.57512623]]
[[0.05815901 0.9418409